# fly.toml app configuration file generated for roe on 2026-03-06T06:19:54-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'roe'
primary_region = 'lhr'
console_command = '/rails/current/bin/rails console'

[build]

[env]
  PORT = '8080'
  SOLID_QUEUE_IN_PUMA = 'true'

[processes]
  app = './bin/rails server'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
