class SnipcartConfig < ApplicationRecord
  TEST_CONFIG_PATH = File.join(RoeSitePaths::SITE_PATH, "system", "integrations", "snipcart.yml")

  enum :mode, { test: 0, live: 1 }, prefix: true

  validates :mode, presence: true

  before_create :set_connected_at

  # AR Encryption — uses master.key. Only live secret key is encrypted
  # since test keys live in the gitignored YAML file.
  encrypts :secret_key_live

  # ── Singleton ────────────────────────────────────────────────────────────

  def self.current
    first_or_create!(mode: :test)
  end

  # ── Snippet accessors (from YAML, public data) ───────────────────────────

  def snippet_test
    full_config["test"]&.fetch("snippet", "")&.strip
  end

  def snippet_live
    full_config["live"]&.fetch("snippet", "")&.strip
  end

  # Active snippet based on mode
  def current_snippet
    mode_test? ? snippet_test : snippet_live
  end

  # ── Secret key accessors ─────────────────────────────────────────────────

  def secret_key_test
    test_config["secret_key"].presence || safe_encrypted_read(:secret_key_test)
  end

  def secret_key_live
    safe_encrypted_read(:secret_key_live)
  end

  # Active secret key based on mode
  def current_secret_key
    mode_test? ? secret_key_test : secret_key_live
  end

  # ── Connection status ────────────────────────────────────────────────────

  def keys_present?
    current_secret_key.present?
  end

  # Verified = keys present AND last API check succeeded
  def connected?
    keys_present? && verified_at.present?
  end

  def live_mode_ready?
    secret_key_live.present?
  end

  # ── API verification ─────────────────────────────────────────────────────

  def verify!
    return false unless keys_present?

    # Use Snipcart orders endpoint — returns 401 on bad key, 200 on valid
    uri = URI("https://app.snipcart.com/api/orders?limit=1")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    http.read_timeout = 10

    request = Net::HTTP::Get.new(uri)
    # Snipcart uses HTTP Basic auth with secret API key as username, empty password
    request.basic_auth(current_secret_key, "")
    request["Accept"] = "application/json"

    response = http.request(request)

    if response.code.to_i == 200
      Rails.logger.info "[SnipcartConfig] verify! succeeded (HTTP 200) in #{mode} mode"
      update_column(:verified_at, Time.current)
      true
    else
      # Snipcart's 4xx responses include a JSON body with an error
      # message — log it so future failures don't silently produce
      # a red badge with no clue why. Truncated to 500 chars to keep
      # the log readable when Snipcart returns a verbose HTML error.
      Rails.logger.warn "[SnipcartConfig] verify! failed: HTTP #{response.code} in #{mode} mode — body: #{response.body.to_s.strip[0, 500].inspect}"
      update_column(:verified_at, nil)
      false
    end
  rescue => e
    Rails.logger.error "[SnipcartConfig] verify! exception: #{e.class}: #{e.message}"
    update_column(:verified_at, nil)
    false
  end

  # ── Disconnect ───────────────────────────────────────────────────────────

  def disconnect!
    update!(
      secret_key_test: nil,
      secret_key_live: nil,
      connected_at: nil,
      verified_at: nil
    )
    self.class.clear_test_config
  end

  # ── Store settings (delegated to store.yml) ──────────────────────────────

  def currency
    SiteConfig.feature("store", "currency") || "usd"
  end

  def default_domain
    SiteConfig.feature("store", "default_domain")
  end

  def load_strategy
    SiteConfig.feature("store", "snipcart.load_strategy") || "on-user-interaction"
  end

  # Snippet HTML — safe to render inline because it's generated by the
  # Snipcart admin panel and stored by the site operator. Not user input.
  def current_snippet_html
    current_snippet&.html_safe
  end

  def modal_style
    SiteConfig.feature("store", "snipcart.modal_style") || "side"
  end

  # ── Full config file (test + live) ───────────────────────────────────────

  def self.full_config
    return {} unless File.exist?(TEST_CONFIG_PATH)
    YAML.load_file(TEST_CONFIG_PATH) || {}
  rescue => e
    Rails.logger.error "Failed to load Snipcart config: #{e.message}"
    {}
  end

  # ── Test config file ─────────────────────────────────────────────────────

  def self.test_config
    full_config["test"] || {}
  end

  def self.save_test_config(config_data)
    FileUtils.mkdir_p(File.dirname(TEST_CONFIG_PATH))
    existing = full_config
    existing["test"] = config_data
    File.write(TEST_CONFIG_PATH, existing.to_yaml.sub(/\A---\s*\n/, ""))
  end

  def self.save_live_snippet(snippet)
    FileUtils.mkdir_p(File.dirname(TEST_CONFIG_PATH))
    existing = full_config
    existing["live"] ||= {}
    existing["live"]["snippet"] = snippet
    File.write(TEST_CONFIG_PATH, existing.to_yaml.sub(/\A---\s*\n/, ""))
  end

  def self.clear_test_config
    File.delete(TEST_CONFIG_PATH) if File.exist?(TEST_CONFIG_PATH)
  end

  # ── Decryption-failure tracking ──────────────────────────────────────────
  # Populated by safe_encrypted_read when an encrypted column can't be
  # decrypted (wrong master key, rotated credentials, corrupted ciphertext).
  # The admin integration view surfaces this so the operator knows to
  # re-save their keys instead of believing the integration is silently
  # disconnected.

  def decryption_errors
    @decryption_errors ||= Set.new
  end

  def decryption_failed?
    decryption_errors.any?
  end

  private

  def test_config
    self.class.test_config
  end

  def full_config
    self.class.full_config
  end

  def safe_encrypted_read(attr)
    self[attr]
  rescue ActiveRecord::Encryption::Errors::Decryption => e
    Rails.logger.warn "#{self.class.name}##{attr} decryption failed: #{e.message}"
    decryption_errors << attr
    nil
  end

  def set_connected_at
    self.connected_at ||= Time.current if current_secret_key.present?
  end
end
