class SnipcartConfig < ApplicationRecord
  TEST_CONFIG_PATH = File.join(RoeSitePaths::SITE_PATH, "system", "integrations", "snipcart.yml")

  enum :mode, { test: 0, live: 1 }, prefix: true

  validates :mode, presence: true

  before_create :set_connected_at

  # ── Singleton ────────────────────────────────────────────────────────────

  def self.current
    first_or_create!(mode: :test)
  end

  # ── Snippet accessors (from YAML, public data) ───────────────────────────

  def snippet_test
    full_config["test"]&.fetch("snippet", "")&.strip
  end

  def snippet_live
    full_config["live"]&.fetch("snippet", "")&.strip
  end

  # Active snippet based on mode
  def current_snippet
    mode_test? ? snippet_test : snippet_live
  end

  # ── Connection status ────────────────────────────────────────────────────
  #
  # Snipcart's store runs entirely on the public snippet (which carries the
  # public API key the client-side widget uses), so "ready/connected" just
  # means the active-mode snippet is set. There is no secret key: the widget
  # needs none, and webhook validation — a future, production-only concern —
  # uses Snipcart's per-request token, not a stored secret.

  def keys_present?
    current_snippet.present?
  end

  def connected?
    keys_present? && verified_at.present?
  end

  def live_mode_ready?
    snippet_live.present?
  end

  # ── Verification ─────────────────────────────────────────────────────────
  #
  # No secret key means there's nothing to check against Snipcart's API —
  # "verified" simply confirms the active snippet is present. Stamps
  # verified_at so the admin connection badge reads "connected" once a
  # snippet is saved.

  def verify!
    if current_snippet.present?
      update_column(:verified_at, Time.current)
      true
    else
      update_column(:verified_at, nil)
      false
    end
  end

  # ── Disconnect ───────────────────────────────────────────────────────────

  def disconnect!
    update!(connected_at: nil, verified_at: nil)
    self.class.clear_test_config
  end

  # ── Store settings (delegated to store.yml) ──────────────────────────────

  def currency
    SiteConfig.feature("store", "currency") || "usd"
  end

  def default_domain
    SiteConfig.feature("store", "default_domain")
  end

  def load_strategy
    SiteConfig.feature("store", "snipcart.load_strategy") || "on-user-interaction"
  end

  # Snippet HTML — safe to render inline because it's generated by the
  # Snipcart admin panel and stored by the site operator. Not user input.
  def current_snippet_html
    current_snippet&.html_safe
  end

  def modal_style
    SiteConfig.feature("store", "snipcart.modal_style") || "side"
  end

  # ── Full config file (test + live) ───────────────────────────────────────

  def self.full_config
    return {} unless File.exist?(TEST_CONFIG_PATH)
    YAML.load_file(TEST_CONFIG_PATH) || {}
  rescue => e
    Rails.logger.error "Failed to load Snipcart config: #{e.message}"
    {}
  end

  # ── Test config file ─────────────────────────────────────────────────────

  def self.test_config
    full_config["test"] || {}
  end

  def self.save_test_config(config_data)
    FileUtils.mkdir_p(File.dirname(TEST_CONFIG_PATH))
    existing = full_config
    existing["test"] = config_data
    File.write(TEST_CONFIG_PATH, existing.to_yaml.sub(/\A---\s*\n/, ""))
  end

  def self.save_live_snippet(snippet)
    FileUtils.mkdir_p(File.dirname(TEST_CONFIG_PATH))
    existing = full_config
    existing["live"] ||= {}
    existing["live"]["snippet"] = snippet
    File.write(TEST_CONFIG_PATH, existing.to_yaml.sub(/\A---\s*\n/, ""))
  end

  def self.clear_test_config
    File.delete(TEST_CONFIG_PATH) if File.exist?(TEST_CONFIG_PATH)
  end

  private

  def test_config
    self.class.test_config
  end

  def full_config
    self.class.full_config
  end

  def set_connected_at
    self.connected_at ||= Time.current if current_snippet.present?
  end
end
